In [3]:
%load_ext autoreload

import os
import sys

print(os.getcwd())
os.chdir(os.path.expanduser('~') + '/Code/navigator')
print(os.getcwd())

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
/home/msc5/Code/vail
/home/msc5/Code/navigator


In [5]:
import rich
from rich import print

In [17]:
w = 64
k, p, s = 4, 1, 2

print(f'{w:10}')
for i in range(5):

    w_new = (w - k + 2 * p) / s + 1
    print(f'{w:10}' + ' -> ' +  f'{w_new:<10}')

    w = w_new

print(f'{w:10}')

        64
        64 -> 32.0      
      32.0 -> 16.0      
      16.0 -> 8.0       
       8.0 -> 4.0       
       4.0 -> 2.0       
       2.0


In [20]:
import torch
import torch.nn as nn

In [24]:
downsample = nn.MaxPool2d(kernel_size=2, return_indices=True)
upsample = nn.MaxUnpool2d(kernel_size=2)

In [30]:
x = torch.rand(1, 6, 6)
y, indices = downsample(x)
z = upsample(y, indices)

print(x.shape)
print(x)

print(y.shape)
print(y)

print(z.shape)
print(z)

torch.Size([1, 6, 6])
tensor([[[0.0336, 0.4048, 0.1990, 0.4420, 0.0704, 0.9134],
         [0.3580, 0.0109, 0.7080, 0.7172, 0.7603, 0.1848],
         [0.7721, 0.8582, 0.7825, 0.5146, 0.4150, 0.4272],
         [0.9890, 0.1025, 0.9370, 0.3434, 0.9760, 0.5619],
         [0.2979, 0.8892, 0.8951, 0.8819, 0.7339, 0.7095],
         [0.4450, 0.1156, 0.9953, 0.4458, 0.5938, 0.8512]]])
torch.Size([1, 3, 3])
tensor([[[0.4048, 0.7172, 0.9134],
         [0.9890, 0.9370, 0.9760],
         [0.8892, 0.9953, 0.8512]]])
torch.Size([1, 6, 6])
tensor([[[0.0000, 0.4048, 0.0000, 0.0000, 0.0000, 0.9134],
         [0.0000, 0.0000, 0.0000, 0.7172, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.9890, 0.0000, 0.9370, 0.0000, 0.9760, 0.0000],
         [0.0000, 0.8892, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.9953, 0.0000, 0.0000, 0.8512]]])
